Repository ngageoint/hootenanny, pull requests merged in 2018-12, with the labels that each got.

#2767 boiler plate updates 11-30-18
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: Category: Documentation

#2772 remove auto-gen'd file
  hoot-core/src/main/cpp/hoot/core/info/VersionDefines.h
Labels: Category: Build

#2797 Remove debug statement
  plugins/TranslationServer.js
Labels: Category: Services, Priority: Medium, Status: Ready for Test, Type: Task, in progress

#2806 Missing UI adv cleaning opts 12/18/18
  conf/services/conflateAdvOps.json
Labels: Category: UI

#2814 Make some Singleton constructors private
  hoot-core/src/main/cpp/hoot/core/Hoot.h
  hoot-core/src/main/cpp/hoot/core/algorithms/ProbabilityOfMatch.h
  hoot-core/src/main/cpp/hoot/core/algorithms/string/MostEnglishName.h
  hoot-core/src/main/cpp/hoot/core/conflate/address/AddressTagKeys.h
  hoot-core/src/main/cpp/hoot/core/conflate/matching/MatchFactory.h
  hoot-core/src/main/cpp/hoot/core/conflate/merging/MergerFactory.h
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonTagIgnoreListReader.h
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonTypeScoreExtractor.cpp
  hoot-core/src/main/cpp/hoot/core/io/OgrUtilities.h
  hoot-core/src/main/cpp/hoot/core/io/OsmChangeWriterFactory.h
  hoot-core/src/main/cpp/hoot/core/io/OsmMapReaderFactory.h
  hoot-core/src/main/cpp/hoot/core/io/OsmMapWriterFactory.h
  hoot-core/src/main/cpp/hoot/core/io/ScriptTranslatorFactory.h
  hoot-core/src/main/cpp/hoot/core/language/TranslateDictionary.h
  hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.h
  hoot-core/src/main/cpp/hoot/core/schema/OsmSchemaLoaderFactory.h
  hoot-core/src/main/cpp/hoot/core/schema/TagComparator.h
  hoot-core/src/main/cpp/hoot/core/schema/TagMergerFactory.h
  hoot-core/src/main/cpp/hoot/core/util/Factory.h
  hoot-core/src/main/cpp/hoot/core/util/HootException.h
  hoot-core/src/main/cpp/hoot/core/util/LibPostalInit.h
  hoot-core/src/main/cpp/hoot/core/util/Log.h
  hoot-core/src/main/cpp/hoot/core/util/MapProjector.h
  hoot-core/src/main/cpp/hoot/core/util/Settings.h
  hoot-core/src/main/cpp/hoot/core/util/SharedPtrPool.h
  hoot-js/src/main/cpp/hoot/js/JsRegistrar.h
  hoot-js/src/main/cpp/hoot/js/algorithms/string/MostEnglishNameJs.h
  hoot-js/src/main/cpp/hoot/js/elements/TagsJs.h
  hoot-js/src/main/cpp/hoot/js/v8Engine.h
  hoot-rnd/src/main/cpp/hoot/rnd/conflate/multiary/MultiaryUtilities.h
  tgs/src/main/cpp/tgs/BigContainers/Stxxl.h
Labels: Category: Core, Type: Maintenance

#2818 Update documentation for command line options, appending and removing.
  docs/HootenannyConfigOptions.asciidoc
  hoot-core/src/main/cpp/hoot/core/util/Settings.cpp
Labels: Category: Documentation, Priority: Low, Type: Task

#2819 Sick of always adding $(nproc) to every HootTest call
  Makefile.hoot
  docs/developer/HootenannyTests.asciidoc
  hoot-test/src/main/cpp/hoot/test/main.cpp
  scripts/TestConfigure.sh
  scripts/jenkins/Jenkinsfile
  scripts/jenkins/TestDevelop.sh
  scripts/jenkins/TestInitialNightly.sh
  scripts/jenkins/TestQuick.sh
  scripts/jenkins/centos67/TestPullRequest_core.sh
Labels: Category: Core, Category: Test, Priority: Low, Type: Feature, Type: Task
