Repository ngageoint/hootenanny, pull requests merged in 2018-04, with the labels that each got.

#2296 Copyright Script updates files that it shouldn't
  scripts/copyright/UpdateCopyrightHeader.py
Labels: Category: Core, Category: Test, Priority: Low, Status: In Progress, Type: Maintenance, Type: Task, in progress

#2303 Added --dumpenum option to the schema scripts
  scripts/schema/ConvertGGDMv30Schema.py
  scripts/schema/ConvertMGCPSchema_XML.py
  scripts/schema/ConvertTDSv40Schema.py
  scripts/schema/ConvertTDSv61Schema.py
  scripts/schema/hootLibrary.py
Labels: Category: Core, Category: Translation, Priority: Low, Status: In Progress, Status: Ready For Review, Type: Task, in progress

#2306 Added c++11 to the standard compile config
  Configure.pri.in
  VagrantProvisionCentOS7.sh
  scripts/jenkins/centos67/VagrantBuild_CentOS67.sh
Labels: Category: Core, Priority: Low, Status: In Progress, Type: Task, in progress

#2301 More less destructive splitting/way creation - SmallWayMerger
  hoot-core/src/main/cpp/hoot/core/conflate/SmallWayMerger.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/SmallWayMerger.h
  hoot-core/src/main/cpp/hoot/core/conflate/splitter/CornerSplitter.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/splitter/DualWaySplitter.h
  hoot-core/src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/splitter/IntersectionSplitter.h
  test-files/cases/hoot-rnd/network/conflicts/highway-012/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-002/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-012/Expected.osm
  test-files/cmd/glacial/NetworkConflateCmdInputReverseTest/output.osm
  test-files/cmd/glacial/NetworkConflateCmdTest/output.osm
  test-files/cmd/glacial/RubberSheetConflateTest/output.osm
  test-files/cmd/glacial/ServiceOsmApiDbHootApiDbRafahConflateTest/output.osm
  test-files/cmd/glacial/serial/ServiceOsmApiDbHootApiDbRafahConflateTest.sh.stdout
  test-files/cmd/slow/ConflateAverageTest/output.osm
Labels: Category: Core, Category: Test, Priority: High, Status: In Progress, Type: Maintenance, Type: Task, in progress

#2307 Roundabout improvements
  hoot-core/src/main/cpp/hoot/core/conflate/RemoveRoundabouts.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/Roundabout.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/Roundabout.h
  test-files/cases/hoot-rnd/roundabouts/rcase-001/Expected.osm
  test-files/cases/hoot-rnd/roundabouts/rcase-001/README.txt
  test-files/cases/hoot-rnd/roundabouts/rcase-002/Expected.osm
  test-files/cases/hoot-rnd/roundabouts/rcase-002/README.txt
  test-files/cases/hoot-rnd/roundabouts/rcase-003/Expected.osm
Labels: Status: In Progress, in progress

#2308 Last instance of the depricated auto_ptr removed
  hoot-js/src/main/cpp/hoot/js/v8Engine.cpp
  hoot-js/src/main/cpp/hoot/js/v8Engine.h
Labels: Category: Core, Priority: Low, Status: In Progress, Type: Task, in progress

#2317 More less destructive splitting/way creation - WaySplitter::createSplits
  hoot-core/src/main/cpp/hoot/core/algorithms/WayMatchStringMerger.cpp
  hoot-core/src/main/cpp/hoot/core/algorithms/WayMatchStringMerger.h
  hoot-core/src/main/cpp/hoot/core/algorithms/WayMatchStringSplitter.cpp
  hoot-core/src/main/cpp/hoot/core/algorithms/WayMatchStringSplitter.h
  hoot-core/src/main/cpp/hoot/core/algorithms/WaySplitter.cpp
  hoot-core/src/main/cpp/hoot/core/algorithms/linearreference/WayMatchStringMapping.h
  hoot-rnd/src/main/cpp/hoot/rnd/conflate/network/PartialNetworkMerger.cpp
  test-files/NonDestructiveTest/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-001/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-004/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-011/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-012/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-013/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-015/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-016/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-017/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-022/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-023/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-025/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-026/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-028/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/highway-030/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-002/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-003/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-004/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-008/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-009/Expected.osm
  test-files/cases/hoot-rnd/network/conflicts/pap-010/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-001/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-004/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-011/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-012/Expected.osm
  test-files/cases/hoot-rnd/network/iterative/highway-013/Expected.osm
  test-files/cases/hoot-rnd/network/single-sided/highway-001/Expected.osm
  test-files/cases/hoot-rnd/network/single-sided/highway-004/Expected.osm
  test-files/cases/hoot-rnd/network/vagabond/highway-001/Expected.osm
  test-files/cases/hoot-rnd/network/vagabond/highway-004/Expected.osm
  test-files/cases/hoot-rnd/roundabouts/rcase-002/Expected.osm
  test-files/cases/hoot-rnd/roundabouts/rcase-003/Expected.osm
  test-files/cmd/glacial/NetworkConflateCmdInputReverseTest/output.osm
  test-files/cmd/glacial/NetworkConflateCmdTest/output.osm
  test-files/cmd/glacial/NonContiguousRoadReviewsTest/output.osm
  test-files/cmd/glacial/NonDestructiveConflationTest.sh
  test-files/cmd/glacial/NonDestructiveConflationTest.sh.stdout
  test-files/cmd/glacial/ServiceOsmApiDbHootApiDbDcStreetsNetworkConflateTest/output.osm
  test-files/cmd/glacial/serial/ServiceOsmApiDbHootApiDbDcStreetsNetworkConflateTest.sh.stdout
Labels: Category: Core, Category: Test, Priority: High, Status: In Progress, Type: Task, in progress

#2325 Translation tweaks for some FCODES
  conf/schema/man_made.json
  conf/schema/natural.json
  plugins/etds40.js
  plugins/test/TranslationServer.js
  plugins/test/line-to-area-cases.js
Labels: Status: In Progress, in progress

#2316 2281 - support land water boundary translation
  conf/schema/natural.json
  plugins/package-lock.json
  plugins/test/TranslationServer.js
Labels: Status: In Progress, in progress

#2341 Poi/poly and implicit tag improvements
  conf/core/ConfigOptions.asciidoc
  conf/core/implicit-tag-rules/implicitTagRulesCustomRuleList
  conf/core/implicit-tag-rules/osm-geonames-4-5-18.sqlite
  conf/schema/emergency.json
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/PoiPolygonReviewReducer.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.cpp
  hoot-core/src/main/cpp/hoot/core/conflate/poi-polygon/extractors/PoiPolygonAddressScoreExtractor.h
  hoot-core/src/main/cpp/hoot/core/io/ImplicitTagRulesSqliteReader.cpp
  hoot-core/src/main/cpp/hoot/core/schema/OsmSchema.cpp
  hoot-core/src/main/cpp/hoot/core/visitors/ImplicitPoiPolygonTypeTagger.cpp
  hoot-core/src/main/cpp/hoot/core/visitors/ImplicitPoiPolygonTypeTagger.h
  hoot-core/src/main/cpp/hoot/core/visitors/ImplicitPoiTypeTagger.cpp
  hoot-core/src/main/cpp/hoot/core/visitors/ImplicitTypeTaggerBase.cpp
  hoot-core/src/main/cpp/hoot/core/visitors/ImplicitTypeTaggerBase.h
  test-files/cmd/glacial/PoiPolygonConflateCombinedTest/output1.osm
  test-files/cmd/glacial/PoiPolygonConflateStandaloneTest/output1.osm
  test-files/cmd/slow/ImplicitTypeTaggerTest.sh.stdout
Labels: Category: Algorithms

#2347 Fixed AQ080 & MGCP AQ125
  plugins/ggdm30.js
  plugins/mgcp.js
  plugins/tds40.js
  plugins/tds61.js
  plugins/test/TranslationServer.js
Labels: Category: Core, Category: Translation, Priority: Medium, Status: In Progress, Status: Ready For Review, Type: Bug, Type: Task, in progress

#2344 Stop religion tags stomping on denominations
  plugins/ggdm30.js
  plugins/tds40.js
  plugins/tds61.js
Labels: Category: Core, Category: Translation, Priority: Medium, Status: In Progress, Type: Bug, in progress
