Repository ngageoint/hootenanny, pull requests merged in 2022-09, with the labels that each got.

#5420 Reorder Jenkins steps to push UI 1 tests to the end for now.
  scripts/jenkins/Jenkinsfile
Labels: Type: Task, Type: Maintenance, Category: Build, Priority: Low

#5424 Add documentation for new hoot-ui open Dataset or Job in JOSM features
  docs/user/Hootenanny-id.asciidoc
Labels: Status: Ready For Review

#5439 Rename `*.oql` files to `*.overpassql`
  conf/services/grailConnectedWaysQuery.overpassql
  conf/services/grailOverpassQuery.overpassql
  hoot-core-test/src/test/cpp/hoot/core/io/OsmJsonReaderTest.cpp
  hoot-services/src/main/java/hoot/services/controllers/grail/PullApiCommand.java
  hoot-services/src/main/resources/conf/hoot-services.conf.in
  hoot-services/src/test/java/hoot/services/controllers/grail/PullApiCommandTest.java
  test-files/io/OsmJsonReaderTest/overpass_query.overpassql
Labels: Type: Task, Type: Maintenance, Category: Core, Category: Services, Category: Test, Priority: Low

#5438 Break out hoot-deps and geoint-deps dependency installation into a separate script
  VagrantProvisionCentOS7.sh
  VagrantProvisionCentOS7Deps.sh
Labels: Type: Task, Type: Maintenance, Category: Core, Category: Install, Priority: Medium

#5427 Add o2s reason
  translations/checkTranslations.js
  translations/dnc_core.js
  translations/ggdm30.js
  translations/mgcp.js
  translations/tds40.js
  translations/tds61.js
  translations/tds70.js
  translations/tds71.js
  translations/test/line-to-area-cases.js
  translations/translate.js
Labels: Type: Feature, Type: Task, Category: Core, Status: Ready for Test, Priority: Medium, Category: Translation, Category: Schema
